# ~/.bashrc: executed by bash(1) for non-login shells.


# Some bash configuration
# -----------------------

# Make things group readable/writable by default
umask 002

source "$HOME/.bashrc.d/environment.sh"

# Source in any local bashrc
if [[ -e ~/.bashrc.local ]] ; then
	source ~/.bashrc.local
fi

# Check for an interactive session
if [[ $-  == *i* ]] ; then

	# Search backwards and forwards through history easier
	bind '"\e[A": history-search-backward'
	bind '"\e[B": history-search-forward'

	# Source in extra scripts
	source "$HOME/.bashrc.d/functions.sh"

	# Unset TMOUT if TMOUT_BUST is set in ~/.bashrc.local
	if [[ -v TMOUT_BUST ]] ; then
		_tmout_bust
		unset TMOUT_BUST
	fi

	source "$HOME/.bashrc.d/python.sh"
	source "$HOME/.bashrc.d/conda.sh"
	source "$HOME/.bashrc.d/haskell.sh"
	source "$HOME/.bashrc.d/venv.sh"

	source "$HOME/.bashrc.d/prompt.sh"
	source "$HOME/.bashrc.d/colours.sh"

	source "$HOME/.bashrc.d/tmux.sh"
	source "$HOME/.bashrc.d/ssh.sh"

	source "$HOME/.bashrc.d/startup.sh"
fi
