#!/bin/bash

set -e

function usage() {
	echo "Usage: $0 [-o|--once]"
}

infinite=true
if [[ $# -eq 0 ]] ; then
	:
elif [[ $# -eq 1 ]] ; then
	case "$1" in
	"-o"|"--once") infinite=false ;;
	"-h"|"--help") usage ; exit ;;
	*)
		echo "Unknown option '$1'" >&2
		usage >&2
		exit 1
	esac
else
	usage >&2
	exit 1
fi

function set_background() {
	find ~/Media/Pictures/Desktops/ -type f \( -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' \) -print0 |
		shuf -n1 -z | xargs -0 feh --bg-fill
}

if $infinite ; then
	while true ; do
		xset q &>/dev/null || break
		set_background
		sleep 10m
	done
else
	set_background
fi
