#!/bin/bash

names=( \
"Nervous Energy" \
"Prosthetic Conscience" \
"Bora Horza Gobuchul" \
"Determinist" \
"Eschatologist" \
"Irregular Apocalypse" \
"No More Mr Nice Guy" \
"Profit Margin" \
"Revisionist" \
"Trade Surplus" \
"The Ends Of Invention" \
"Clear Air Turbulence" \
"The Hand of God 137" \
"Screw Loose" \
"Flexible Demeanour" \
"Just Read The Instructions" \
"Of Course I Still Love You" \
"Limiting Factor" \
"Cargo Cult" \
"Little Rascal" \
"So Much For Subtlety" \
"Unfortunate Conflict Of Evidence" \
"Youthful Indiscretion" \
"Gunboat Diplomat" \
"Zealot" \
"Kiss My Ass" \
"Prime Mover" \
"Invincible" \
"Just Testing" \
"Xenophobe" \
"Very Little Gravitas Indeed" \
"What Are The Civilian Applications?" \
"Congenital Optimist" \
"Size Isn't Everything" \
"Sweet and Full of Grace" \
"Bad for Business" \
"Arbitrary" \
"Cantankerous" \
"Only Slightly Bent" \
"I Thought He Was With You" \
"Space Monster" \
"A Series Of Unlikely Explanations" \
"Big Sexy Beast" \
"Never Talk To Strangers" \
"Funny, It Worked Last Time..." \
"Boo!" \
"Ultimate Ship The Second" \
"It'll Be Over By Christmas" \
"A Ship With A View" \
"Ablation" \
"Arrested Development" \
"Credibility Problem" \
"Dramatic Exit, Or, Thank you And Goodnight" \
"Excuses And Accusations" \
"God Told Me To Do It" \
"Halation Effect" \
"Happy Idiot Talk " \
"Helpless In The Face Of Your Beauty" \
"Heresiarch" \
"Just Another Victim Of The Ambient Morality" \
"Minority Report" \
"Not Wanted On Voyage" \
"Perfidy" \
"Sacrificial Victim" \
"Stranger Here Myself" \
"Synchronize Your Dogmas" \
"The Precise Nature Of The Catastrophe" \
"Unwitting Accomplice" \
"Undesirable Alien" \
"Well I Was In The Neighbourhood" \
"You Would If You Really Loved Me" \
"You'll Thank Me Later" \
"Different Tan" \
"Fate Amenable To Change" \
"Grey Area" \
"It's Character Forming" \
"Jaundiced Outlook" \
"Problem Child" \
"Reasonable Excuse" \
"Recent Convert" \
"Tactical Grace" \
"Unacceptable Behaviour" \
"Steely Glint" \
"Highpoint" \
"Shoot Them Later" \
"Attitude Adjuster" \
"Killing Time" \
"Heavy Messing" \
"Frank Exchange Of Views" \
"Anticipation Of A New Lover's Arrival, The" \
"Death and Gravity" \
"Ethics Gradient" \
"Honest Mistake" \
"Limivorous" \
"No Fixed Abode" \
"Quietly Confident," \
"later Sleeper Service" \
"Uninvited Guest" \
"Use Psychology" \
"What Is The Answer and Why?" \
"Wisdom Like Silence" \
"Yawning Angel" \
"Zero Gravitas" \
"Misophist" \
"Serious Callers Only" \
"Not Invented Here" \
"Charitable View" \
"I Blame My Mother" \
"I Blame Your Mother" \
"Just Passing Through" \
"Full Refund" \
"Appeal To Reason" \
"Break Even" \
"Long View" \
"Peace Makes Plenty" \
"Sober Counsel" \
"Within Reason" \
"Kiss the Blade" \
"Frightspear" \
"Furious Purpose" \
"Riptalon" \
"Wingclipper" \
"SacSlicer II" \
"Xenoclast" \
"Winter Storm" \
"Piety" \
"Soulhaven" \
"Nuisance Value" \
"Vulgarian" \
"Sanctioned Parts List" \
"Resistance Is Character-Forming" \
"All Through With This Niceness And Negotiation Stuff" \
"Someone Else's Problem" \
"Lacking That Small Match Temperament" \
"Poke It With A Stick" \
"I Said, I've Got A Big Stick" \
"Hand Me The Gun And Ask Me Again" \
"But Who's Counting?" \
"Germane Riposte" \
"We Haven't Met But You're A Great Fan Of Mine" \
"All The Same, I Saw It First" \
"Ravished By The Sheer Implausibility Of That Last Statement" \
"Zero Credibility" \
"Charming But Irrational" \
"Demented But Determined" \
"You May Not Be The Coolest Person Here" \
"Lucid Nonsense" \
"Awkward Customer" \
"Thorough But... Unreliable" \
"Advanced Case Of Chronic Patheticism" \
"Another Fine Product From The Nonsense Factory" \
"Conventional Wisdom" \
"In One Ear" \
"Fine Till You Came Along" \
"I Blame The Parents" \
"Inappropriate Response" \
"A Momentary Lapse Of Sanity" \
"Lapsed Pacifist" \
"Reformed Nice Guy" \
"Pride Comes Before A Fall" \
"Injury Time" \
"Now Look What You've Made Me Do" \
"Kiss This Then" \
"Lasting Damage" \
"Lasting Damage I" \
"Lasting Damage II" \
"Experiencing A Significant Gravitas Shortfall" \
"Don't Try This At Home" \
"Eight Rounds Rapid" \
"Experiencing A Significant Gravitas Shortfall" \
"It's My Party And I'll Sing If I Want To" \
"Lightly Seared On The Reality Grill" \
"Now We Try It My Way" \
"Liveware Problem" \
"Pure Big Mad Boat Man" \
"Qualifier" \
"Seed Drill" \
"Subtle Shift In Emphasis" \
"Transient Atmospheric Phenomenon" \
"Xenoglossicist" \
"You Naughty Monsters" \
"You'll Clean That Up Before You Leave" \
"Hence the Fortress" \
"Hundredth Idiot, The" \
"Fasilyce, Upon Waking" \
"Inspiral, Coalescence, Ringdown" \
"On First Seeing Jhiriit" \
"Now, Turning to Reason, & Its Just Sweetness" \
"Sense Amid Madness, Wit Amidst Folly" \
"Me, I'm Counting" \
"Bodhisattva, OAQS" \
"Total Internal Reflection" \
"Armchair Traveller" \
"The Usual But Etymologically Unsatisfactory" \
"Hidden Income" \
"Falling Outside The Normal Moral Constraints" \
"Hylozoist" \
"No One Knows What The Dead Think" \
"Pelagian" \
"Ucalegon" \
"Messenger Of Truth" \
"Fractious Person" \
"Rubric Of Ruin" \
"Abundance Of Onslaught" \
"Vision Of Hope Surpassed" \
"8401.00 Partial Photic Boundary" \
"Mistake Not…" \
"Questionable Ethics" \
"New Toy" \
"Learned Response" \
"Caconym" \
"Pressure Drop" \
"Kakistocrat" \
"Passing By And Thought I'd Drop In" \
"Empiricist" \
"Refreshingly Unconcerned With the Vulgar Exigencies of Veracity" \
"Value Judgement" \
"Beats Working" \
"Headcrash" \
"Xenocrat" \
"Contents May Differ" \
"Just the Washing Instruction Chip in Life's Rich Tapestry" \
"Displacement Activity" \
"Anything Legal Considered" \
"Zoologist" \
"Warm, Considering" \
"A Fine Disregard for Awkward Facts" \
"Teething Problems" \
"Outstanding Contribution to the Historical Process" \
"Rapid Random Response Unit" \
"Smile Tolerantly" \
"Unreliable Witness" \
"You Call This Clean?" \
"5*Gelish-Oplule" \
"7*Uagren" \
"8*Churkun" \
"Gellemtyan-Asool-Anafawaya" \
"Quiatrea-Anang" \
"Laskuil-Hliz" \
"Abalule-Sheliz" \
"Fulanya-Guang" \
"Exaltation-Parsimony III" \
"Oceanic Dissonance" \
"Melancholia Enshrines All Triumph" \
"Strategic Outreach Element CH2OH.(CHOH)4.CHO" \
)

name="${names[$RANDOM % ${#names[@]} ]}"

while [ $# -ne 0 ] ; do
	message_format="${1:-workspace %s}"
	i3-msg $( printf "$message_format" "$name" )
	shift
done
