#!/bin/bash

while true ; do
	xset q &>/dev/null || break

	find ~/Media/Pictures/Desktops/ -type f \( -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' \) -print0 |
		shuf -n1 -z | xargs -0 feh --bg-fill

	sleep 10m
done
