#!/bin/bash

function cmd? {
	command -V "$1" &>/dev/null && "$@"
}

# Window compositor
( cmd? compton || cmd? xcompmgr ) &

cmd? nm-applet &
cmd? ~/.i3/background &
cmd? xfce4-power-manager &
cmd? xfce4-volumed &

cmd? ~/.i3/startup.local && ~/.i3/startup.local
