#!/bin/bash

function cmd? {
	command -V "$1" &>/dev/null && ( "$@" & )
}

# Window compositor
( cmd? compton || cmd? xcompmgr ) &

cmd? nm-applet
cmd? cmst --minimized || cmd? connman-ui-gtk
cmd? ~/.i3/background
cmd? xfce4-power-manager
cmd? volumeicon

cmd? ~/.bin/setup_external_monitor
cmd? ~/.i3/startup.local
